- platform: template
  sensors:
    cats_ipad:
      value_template: "{{ 'Online' if is_state('device_tracker.catherinesipad', 'home') else 'Offline' }}"
      
    gaming_pc:
      value_template: "{{ 'Online' if is_state('device_tracker.gamingpc', 'home') else 'Offline' }}"

    harmony_hub:
      value_template: "{{ 'Online' if is_state('device_tracker.harmonyhub', 'home') else 'Offline' }}"

    kindle_tablet:
      value_template: "{{ 'Online' if is_state('device_tracker.kindle-fire7', 'home') else 'Offline' }}"

    zyxel_nsa310:
      value_template: "{{ 'Online' if is_state('device_tracker.nsa310', 'home') else 'Offline' }}"

    lounge_kodi:
      value_template: "{{ 'Online' if is_state('device_tracker.osmc', 'home') else 'Offline' }}"

    steam_link:
      value_template: "{{ 'Online' if is_state('device_tracker.steam_link', 'home') else 'Offline' }}"

    hue_hub:
      value_template: "{{ 'Online' if is_state('device_tracker.hugo', 'home') else 'Offline' }}"

    tado_bridge:
      value_template: "{{ 'Online' if is_state('device_tracker.tado_bridge_v3', 'home') else 'Offline' }}"

    daves_sp4:
      value_template: "{{ 'Online' if is_state('device_tracker.davessp4', 'home') else 'Offline' }}"
