- platform: systemmonitor
  resources:
    - type: processor_use
    - type: last_boot
    - type: since_last_boot
    - type: memory_use_percent
    - type: disk_use_percent
      arg: /

- platform: cert_expiry
  host: !secret HASS_URL

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'time_utc'