#####################################################
#
#  Disable lights_on_after_hours automation
#
#####################################################
- alias: Disable lights_on_after_hours automation
  initial_state: true
  hide_entity: false
  trigger:
    platform: state
    entity_id: device_tracker.catsiphone
    from: 'not_home'
    to: 'home'
    for:
      minutes: 10
  condition:
    condition: time
    after: '21:00:00'
    before: '06:00:00'
  action:
    - service: automation.turn_off
      entity_id: automation.lights_on_after_hours

#####################################################
#
#  Enable lights_on_after_hours automation at
#  9pm if Cat is not home
#
#####################################################
- alias: Enable lights_on_after_hours automation
  initial_state: true
  hide_entity: false
  trigger:
    platform: time
    after: '21:00:00'
  condition:
    condition: state
    entity_id: device_tracker.catsiphone
    state: 'not_home'
  action:
    - service: automation.turn_on
      entity_id: automation.lights_on_after_hours
