#####################################################
#
#  Switch on lights if nobody home at sunset
#
#####################################################
- alias: Lights on at sunset if not home
  initial_state: true
  hide_entity: false
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: state
    entity_id: group.family
    state: 'not_home' 
  action:
    - service: scene.turn_on
      entity_id: scene.not_home
    - service: notify.ios_daves_iphone
      data:
        message: 'There is no one home so I have switched on the lights ready for you to arrive home.'

#####################################################
#
#  Switch on lights 1 hour before sunset if at home and GMT
#
#####################################################
- alias: Lights on 1hr before sunset if home GMT
  initial_state: true
  hide_entity: false
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  condition:
    condition: and
    conditions:
     - condition: state
       entity_id: group.family
       state: 'home'
     - condition: state
       entity_id: binary_sensor.bst
       state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.daytime
    - service: notify.ios_daves_iphone
      data:
        message: 'It is 1 hour until sunset so I have switched on the lights for you.'

#####################################################
#
#  Switch on lights 15 minutes before sunset if at home and BST
#
#####################################################
- alias: Lights on 1hr before sunset if home BST
  initial_state: true
  hide_entity: false
  trigger:
    platform: sun
    event: sunset
    offset: '-00:15:00'
  condition:
    condition: and
    conditions:
     - condition: state
       entity_id: group.family
       state: 'home'
     - condition: state
       entity_id: binary_sensor.bst
       state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.daytime
    - service: notify.ios_daves_iphone
      data:
        message: 'It is 15 minutes until sunset so I have switched on the lights for you.'

#####################################################
#
#  Switch on lights when someone arrives home and 
#  nobody is already home or lights are off
#
#####################################################
- alias: Lights on arrive home
  initial_state: true
  hide_entity: false
  trigger:
    platform: state
    entity_id: group.family
    from: 'not_home'
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
        after_offset: '-01:00:00'
      - condition: state
        entity_id: group.lounge_lights
        state: 'off'
      - condition: state
        entity_id: group.dining_room_lights
        state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.daytime
    - service: notify.ios_daves_iphone
      data:
        message: 'Welcome home, I have switched on the lights for you.'
    - delay: 00:10:00 
    - service: light.turn_off
      entity_id: light.front_door_light

#####################################################
#
#  Switch on front door light when Cat arrives
#  home after 10pm
#
#####################################################
- alias: Lights on after hours
  initial_state: false
  hide_entity: false
  trigger:
    - platform: state
      entity_id: device_tracker.catsiphone
      from: 'not_home'      
      to: 'home'
  condition:
    - condition: time
      after: '22:00:00'
      before: '06:00:00'
  action:
    - service: scene.turn_on
      entity_id: scene.after_hours
    - delay: 00:10:00
    - service: light.turn_off
      entity_id: light.front_door_light    
  
#####################################################
#
#  Switch off lights during the day when
#  everyone leaves the house but only when
#  guest mode is disabled
#
#####################################################
- alias: Lights off all leave home
  initial_state: true
  hide_entity: false
  trigger:
    platform: state
    entity_id: group.family
    from: 'home'
    to: 'not_home'
    for:
      minutes: 5
  condition:
    condition: and
    conditions:
      - condition: time
        after: '07:00:00'
      - condition: sun
        before: sunset
        before_offset: "-00:15:00"
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: notify.ios_daves_iphone
      data:
        message: 'There is no one at home so I have switched off the lights for you.'

#####################################################
#
#  Switch on landing light at 9pm ready for bed
#
#####################################################
- alias: Landing Light on Bedtime
  initial_state: true
  hide_entity: false
  trigger:
    platform: time
    after: '21:00:00'
  condition:
    condition: state
    entity_id: group.family
    state: 'home' 
  action:
    - service: scene.turn_on
      entity_id: scene.bedtime