#####################################################
#
#  Switch on lights if nobody home at sunset
#
#####################################################
- alias: Lights on at sunset if not home
  initial_state: true
  hide_entity: false
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: state
    entity_id: group.family
    state: 'not_home' 
  action:
    - service: scene.turn_on
      entity_id: scene.not_home
    - service: notify.ios_daves_iphone
      data:
        message: 'There is no one home so I have switched on the lights ready for you to arrive home.'

#####################################################
#
#  Switch on lights 1 hour before sunset if at home and GMT
#
#####################################################
- alias: Lights on 1hr before sunset if home GMT
  initial_state: true
  hide_entity: false
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  condition:
    condition: and
    conditions:
     - condition: state
       entity_id: group.family
       state: 'home'
#     - condition: state
#       entity_id: binary_sensor.bst
#       state: 'off'
  action:
#    - service: scene.turn_on
#      entity_id: scene.evening_downstairs
    - service: light.turn_on
      data:
        entity_id: group.lounge_lights
        brightness: 255
    - service: light.turn_on
      data:
        entity_id: group.dining_room_lights
        brightness: 255
    - service: notify.ios_daves_iphone
      data:
        message: 'It is 1 hour until sunset so I have switched on the lights for you.'

#####################################################
#
#  Switch on lights when someone arrives home and nobody is already home or lights are off
#
#####################################################
- alias: Lights on arrive home
  initial_state: true
  hide_entity: false
  trigger:
    platform: state
    entity_id: group.family
    from: 'not_home'
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
        after_offset: '-01:00:00'
      - condition: state
        entity_id: group.lounge_lights
        state: 'off'
      - condition: state
        entity_id: group.dining_room_lights
        state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: group.lounge_lights
        brightness: 255
    - service: light.turn_on
      data:
        entity_id: group.dining_room_lights
        brightness: 255
    - service: light.turn_on
      data:
        entity_id: light.landing_light
        brightness: 200
#   - service: scene.turn_on
#     entity_id: scene.evening_downstairs
    - service: switch.turn_on
      entity_id: switch.sonoff_power_1
    - service: notify.ios_daves_iphone
      data:
        message: 'Welcome home, I have switched on the lights for you.'
    - delay: 00:10:00 
    - service: light.turn_off
      entity_id: light.front_door_light

#####################################################
#
#  Switch on front door light when Cat arrives home after 10pm
#
#####################################################
- alias: Lights on after hours
  initial_state: false
  hide_entity: false
  trigger:
    - platform: state
      entity_id: device_tracker.catsiphone
      from: 'not_home'      
      to: 'home'
  condition:
    - condition: time
      after: '22:00:00'
      before: '06:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.front_door_light
        brightness: 1
    - delay: 00:10:00
    - service: light.turn_off
      entity_id: light.front_door_light    
  
#####################################################
#
#  Switch off lights during the day when
#  everyone leaves the house but only when
#  guest mode is disabled
#
#####################################################
- alias: Lights off all leave home
  initial_state: true
  hide_entity: false
  trigger:
    platform: state
    entity_id: group.family
    from: 'home'
    to: 'not_home'
    for:
      minutes: 5
  condition:
    condition: and
    conditions:
      - condition: time
        after: '07:00:00'
      - condition: sun
        before: sunset
        before_offset: "-00:15:00"
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: group.lights
        state: 'on'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: switch.turn_off
      entity_id: switch.sonoff_power_1
    - service: notify.ios_daves_iphone
      data:
        message: 'There is no one at home and some lights where left on, so I have switched off the lights for you.'

#####################################################
#
#  Switch on landing light at 9pm ready for bed
#
#####################################################
- alias: Landing Light on Bedtime
  initial_state: true
  hide_entity: false
  trigger:
    platform: time
    at: '21:00:00'
  condition:
    condition: state
    entity_id: group.family
    state: 'home' 
  action:
    - service: scene.turn_on
      entity_id: scene.bedtime

#####################################################
#
#  Switch on lights 1hr before sunset if Guest Mode Enabled
#
#####################################################
- alias: Guest Mode Lights on 1hr before sunset
  initial_state: false
  hide_entity: false
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  action:
    - service: scene.turn_on
      entity_id: scene.evening_downstairs

#####################################################
#
#  Switch off downstairs lights at 9am
#
#####################################################
- alias: Downstairs lights off at 9am
  initial_state: false
  hide_entity: false
  trigger:
    platform: time
    at: '09:00:00' 
  action:
    - service: light.turn_off
      entity_id: group.lounge_lights
    - service: light.turn_off
      entity_id: group.dining_room_lights


#####################################################
#
#  Set Bathroom on after motion detected early morning
#
#####################################################
- alias: Bathroom Lights on after motion detected early morning
  initial_state: true
  hide_entity: false
  trigger:
    - platform: state
      entity_id: sensor.bathroom_motion_binary
      from: 'False'
      to: 'True'
  condition:
    - condition: time
      after: '05:30:00'
      before: '06:45:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bathroom_light
        brightness: 200
        transition: 180
        rgb_color: [255, 189, 86]

#####################################################
#
#  Set Bathroom on after motion detected during daytime
#
#####################################################
- alias: Bathroom Lights on after motion detected daytime
  initial_state: true
  hide_entity: false
  trigger:
    platform: state
    entity_id: sensor.bathroom_motion_binary
    from: 'False'
    to: 'True'
  condition:
    - condition: time
      after: '06:45:00'
      before: '22:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bathroom_light
        brightness: 254
        rgb_color: [255, 211, 135]

#####################################################
#
#  Set Bathroom and landing lights on after motion detected at night
#
#####################################################
- alias: Bathroom Lights on after motion detected at night
  initial_state: true
  hide_entity: false
  trigger:
    - platform: state
      entity_id: sensor.bathroom_motion_binary
      from: 'False'
      to: 'True'
  condition:
    - condition: time
      after: '22:00:00'
      before: '05:30:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bathroom_light
        brightness: 200
        rgb_color: [255, 0, 0]
    - service: light.turn_on
      data:
        entity_id: light.landing_light
        brightness: 1
        rgb_color: [255, 0, 0]

#####################################################
#
#  Turn off Bathroom light 5 minutes after last motion detected
#
#####################################################
- alias: Bathroom Lights off 5 mins after motion detected
  initial_state: true
  hide_entity: false
  trigger:
    - platform: state
      entity_id: sensor.bathroom_motion_binary
      from: 'True'
      to: 'False'
      for:
        minutes: 4
  condition:
    condition: or
    conditions:
      - condition: time
        after: '09:00:00'
        before: '18:00:00'
      - condition: time
        after: '19:00:00'
        before: '05:30:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bathroom
        brightness: 150
    - delay: 00:01:00
    - service: light.turn_off
      entity_id: light.bathroom_light


#####################################################
#
#  Turn off Bathroom light 15 minutes after last motion detected
#
#####################################################
- alias: Bathroom Lights off 15 mins after motion detected
  initial_state: true
  hide_entity: false
  trigger:
    - platform: state
      entity_id: sensor.bathroom_motion_binary
      from: 'True'
      to: 'False'
      for:
        minutes: 14
  condition:
    - condition: time
      after: '18:00:00'
      before: '19:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bathroom
        brightness: 150
    - delay: 00:01:00
    - service: light.turn_off
      entity_id: light.bathroom_light

#####################################################
#
#  Turn off Bathroom light 15 minutes after last motion detected
#
#####################################################
- alias: Bathroom Lights off 19 mins after motion detected
  initial_state: true
  hide_entity: false
  trigger:
    - platform: state
      entity_id: sensor.bathroom_motion_binary
      from: 'True'
      to: 'False'
      for:
        minutes: 9
  condition:
    - condition: time
      after: '05:30:00'
      before: '09:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bathroom
        brightness: 150
    - delay: 00:01:00 
    - service: light.turn_off
      entity_id: light.bathroom_light

#####################################################
#
#  Turn off landing light 1 minute after being switched on at night
#
#####################################################
- alias: Landing light off after 1 minutes at night
  initial_state: true
  hide_entity: false
  trigger:
    - platform: state
      entity_id: light.landing_light
      from: 'off'
      to: 'on'
      for:
        minutes: 1
  condition:
    - condition: time
      after: '22:00:00'
      before: '05:30:00'
  action:
    - service: light.turn_off
      entity_id: light.landing_light